package com.mycompany.sistemkepegawaian.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AbsensiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbsensiAllPropertiesEquals(Absensi expected, Absensi actual) {
        assertAbsensiAutoGeneratedPropertiesEquals(expected, actual);
        assertAbsensiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbsensiAllUpdatablePropertiesEquals(Absensi expected, Absensi actual) {
        assertAbsensiUpdatableFieldsEquals(expected, actual);
        assertAbsensiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbsensiAutoGeneratedPropertiesEquals(Absensi expected, Absensi actual) {
        assertThat(actual)
            .as("Verify Absensi auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbsensiUpdatableFieldsEquals(Absensi expected, Absensi actual) {
        assertThat(actual)
            .as("Verify Absensi relevant properties")
            .satisfies(a -> assertThat(a.getTanggal()).as("check tanggal").isEqualTo(expected.getTanggal()))
            .satisfies(a -> assertThat(a.getJamMasuk()).as("check jamMasuk").isEqualTo(expected.getJamMasuk()))
            .satisfies(a -> assertThat(a.getJamKeluar()).as("check jamKeluar").isEqualTo(expected.getJamKeluar()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAbsensiUpdatableRelationshipsEquals(Absensi expected, Absensi actual) {
        assertThat(actual)
            .as("Verify Absensi relationships")
            .satisfies(a -> assertThat(a.getPegawai()).as("check pegawai").isEqualTo(expected.getPegawai()));
    }
}
