package com.mycompany.sistemkepegawaian.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CutiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCutiAllPropertiesEquals(Cuti expected, Cuti actual) {
        assertCutiAutoGeneratedPropertiesEquals(expected, actual);
        assertCutiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCutiAllUpdatablePropertiesEquals(Cuti expected, Cuti actual) {
        assertCutiUpdatableFieldsEquals(expected, actual);
        assertCutiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCutiAutoGeneratedPropertiesEquals(Cuti expected, Cuti actual) {
        assertThat(actual)
            .as("Verify Cuti auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCutiUpdatableFieldsEquals(Cuti expected, Cuti actual) {
        assertThat(actual)
            .as("Verify Cuti relevant properties")
            .satisfies(a -> assertThat(a.getTanggalMulai()).as("check tanggalMulai").isEqualTo(expected.getTanggalMulai()))
            .satisfies(a -> assertThat(a.getTanggalSelesai()).as("check tanggalSelesai").isEqualTo(expected.getTanggalSelesai()))
            .satisfies(a -> assertThat(a.getAlasan()).as("check alasan").isEqualTo(expected.getAlasan()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCutiUpdatableRelationshipsEquals(Cuti expected, Cuti actual) {
        assertThat(actual)
            .as("Verify Cuti relationships")
            .satisfies(a -> assertThat(a.getPegawai()).as("check pegawai").isEqualTo(expected.getPegawai()));
    }
}
