package com.mycompany.sistemkepegawaian.domain;

import static com.mycompany.sistemkepegawaian.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PegawaiAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPegawaiAllPropertiesEquals(Pegawai expected, Pegawai actual) {
        assertPegawaiAutoGeneratedPropertiesEquals(expected, actual);
        assertPegawaiAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPegawaiAllUpdatablePropertiesEquals(Pegawai expected, Pegawai actual) {
        assertPegawaiUpdatableFieldsEquals(expected, actual);
        assertPegawaiUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPegawaiAutoGeneratedPropertiesEquals(Pegawai expected, Pegawai actual) {
        assertThat(actual)
            .as("Verify Pegawai auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPegawaiUpdatableFieldsEquals(Pegawai expected, Pegawai actual) {
        assertThat(actual)
            .as("Verify Pegawai relevant properties")
            .satisfies(a -> assertThat(a.getNama()).as("check nama").isEqualTo(expected.getNama()))
            .satisfies(a -> assertThat(a.getJabatan()).as("check jabatan").isEqualTo(expected.getJabatan()))
            .satisfies(a -> assertThat(a.getDepartemen()).as("check departemen").isEqualTo(expected.getDepartemen()))
            .satisfies(a -> assertThat(a.getGaji()).as("check gaji").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getGaji()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPegawaiUpdatableRelationshipsEquals(Pegawai expected, Pegawai actual) {
        // empty method
    }
}
