package com.mycompany.sistemkepegawaian.domain;

import static com.mycompany.sistemkepegawaian.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PenggajianAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPenggajianAllPropertiesEquals(Penggajian expected, Penggajian actual) {
        assertPenggajianAutoGeneratedPropertiesEquals(expected, actual);
        assertPenggajianAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPenggajianAllUpdatablePropertiesEquals(Penggajian expected, Penggajian actual) {
        assertPenggajianUpdatableFieldsEquals(expected, actual);
        assertPenggajianUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPenggajianAutoGeneratedPropertiesEquals(Penggajian expected, Penggajian actual) {
        assertThat(actual)
            .as("Verify Penggajian auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPenggajianUpdatableFieldsEquals(Penggajian expected, Penggajian actual) {
        assertThat(actual)
            .as("Verify Penggajian relevant properties")
            .satisfies(a -> assertThat(a.getBulan()).as("check bulan").isEqualTo(expected.getBulan()))
            .satisfies(a ->
                assertThat(a.getGajiPokok()).as("check gajiPokok").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getGajiPokok())
            )
            .satisfies(a -> assertThat(a.getBonus()).as("check bonus").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBonus()))
            .satisfies(a ->
                assertThat(a.getPotongan()).as("check potongan").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPotongan())
            )
            .satisfies(a ->
                assertThat(a.getTotalGaji()).as("check totalGaji").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotalGaji())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPenggajianUpdatableRelationshipsEquals(Penggajian expected, Penggajian actual) {
        assertThat(actual)
            .as("Verify Penggajian relationships")
            .satisfies(a -> assertThat(a.getPegawai()).as("check pegawai").isEqualTo(expected.getPegawai()));
    }
}
